# Analisi statistica F1

L'utilizzo delle API di **`OpenF1`** è consigliato per l'uso di dati recenti e legati alla **telemetria**, mentre per le API di **`F1API`** sono dati **storici** risalenti fino alla prima gara nel 1950. I dati di **OpenF1** Vengono aggiornati alla mezzanotte (UTC) della fine dell'evento. Mentre per **F1API** I dati vengono aggiornati con i risultati dopo 24/48h dal termine dell'evento.

In [ ]:
from urllib.request import urlopen
from urllib.parse import urlencode
import json
import pandas as pd
from pitstat import get_data

In [ ]:
df = get_data('2026/15/race', api='f1api')
df

,season,raceId,raceName,round,date,position,points,grid,time,fastLap,...,driver.surname,driver.nationality,driver.birthday,team.teamId,team.teamName,team.nationality,team.firstAppareance,team.constructorsChampionships,team.driversChampionships,team.url
0,2026,azerbaijan_2026,Formula 1 Qatar Airways Azerbaijan Grand Prix ...,15,2026-09-26,1,25,1,1:38:02.143,1:44.916,...,Russell,Great Britain,15/02/1998,mercedes,Mercedes Formula 1 Team,Germany,1954,8.0,9.0,https://en.wikipedia.org/wiki/Mercedes-Benz_in...
1,2026,azerbaijan_2026,Formula 1 Qatar Airways Azerbaijan Grand Prix ...,15,2026-09-26,2,18,8,+0.196,1:44.993,...,Verstappen,Netherlands,1997-09-30,red_bull,Red Bull Racing,Austria,2005,6.0,8.0,https://en.wikipedia.org/wiki/Red_Bull_Racing
2,2026,azerbaijan_2026,Formula 1 Qatar Airways Azerbaijan Grand Prix ...,15,2026-09-26,3,15,4,+10.704,1:45.618,...,Hadjar,France,2004-02-28,red_bull,Red Bull Racing,Austria,2005,6.0,8.0,https://en.wikipedia.org/wiki/Red_Bull_Racing
3,2026,azerbaijan_2026,Formula 1 Qatar Airways Azerbaijan Grand Prix ...,15,2026-09-26,4,12,2,+14.136,1:45.784,...,Leclerc,Monaco,16/10/1997,ferrari,Scuderia Ferrari,Italy,1950,16.0,15.0,https://en.wikipedia.org/wiki/Scuderia_Ferrari
4,2026,azerbaijan_2026,Formula 1 Qatar Airways Azerbaijan Grand Prix ...,15,2026-09-26,5,10,16,+14.512,1:45.413,...,Kimi Antonelli,Italy,2006-08-25,mercedes,Mercedes Formula 1 Team,Germany,1954,8.0,9.0,https://en.wikipedia.org/wiki/Mercedes-Benz_in...
5,2026,azerbaijan_2026,Formula 1 Qatar Airways Azerbaijan Grand Prix ...,15,2026-09-26,6,8,6,+22.382,1:46.170,...,Hamilton,Great Britain,07/01/1985,ferrari,Scuderia Ferrari,Italy,1950,16.0,15.0,https://en.wikipedia.org/wiki/Scuderia_Ferrari
6,2026,azerbaijan_2026,Formula 1 Qatar Airways Azerbaijan Grand Prix ...,15,2026-09-26,7,6,15,+31.159,1:46.849,...,Lindblad,Great Britain,2007-08-07,rb,RB F1 Team,Italy,2024,NaN,NaN,https://en.wikipedia.org/wiki/RB_Formula_One_Team
7,2026,azerbaijan_2026,Formula 1 Qatar Airways Azerbaijan Grand Prix ...,15,2026-09-26,8,4,13,+31.189,1:47.068,...,Ocon,France,17/09/1996,haas,Haas F1 Team,United States,2016,NaN,NaN,https://en.wikipedia.org/wiki/Haas_F1_Team
8,2026,azerbaijan_2026,Formula 1 Qatar Airways Azerbaijan Grand Prix ...,15,2026-09-26,9,2,10,+31.929,1:46.978,...,Bearman,Great Britain,08/05/2005,haas,Haas F1 Team,United States,2016,NaN,NaN,https://en.wikipedia.org/wiki/Haas_F1_Team
9,2026,azerbaijan_2026,Formula 1 Qatar Airways Azerbaijan Grand Prix ...,15,2026-09-26,10,1,14,+32.416,1:46.737,...,Sainz,Spain,01/09/1994,williams,Williams Racing,Great Britain,1977,9.0,7.0,https://en.wikipedia.org/wiki/Williams_Grand_P...
10,2026,azerbaijan_2026,Formula 1 Qatar Airways Azerbaijan Grand Prix ...,15,2026-09-26,11,0,18,+33.231,1:46.850,...,Hulkenberg,Germany,19/08/1987,audi,Audi Revolut F1 Team,Germany,2026,NaN,NaN,https://en.wikipedia.org/wiki/Audi_in_Formula_One
11,2026,azerbaijan_2026,Formula 1 Qatar Airways Azerbaijan Grand Prix ...,15,2026-09-26,12,0,11,+34.013,1:46.906,...,Lawson,New Zealand,2002-02-11,rb,RB F1 Team,Italy,2024,NaN,NaN,https://en.wikipedia.org/wiki/RB_Formula_One_Team
12,2026,azerbaijan_2026,Formula 1 Qatar Airways Azerbaijan Grand Prix ...,15,2026-09-26,13,0,3,+36.401,1:46.602,...,Piastri,Australia,06/04/2001,mclaren,McLaren Formula 1 Team,Great Britain,1966,10.0,13.0,https://en.wikipedia.org/wiki/McLaren
13,2026,azerbaijan_2026,Formula 1 Qatar Airways Azerbaijan Grand Prix ...,15,2026-09-26,14,0,20,+41.400,1:47.363,...,Pérez,Mexico,1990-01-26,cadillac,Cadillac Formula 1 Team,United States,2026,NaN,NaN,https://en.wikipedia.org/wiki/Cadillac_in_Form...
14,2026,azerbaijan_2026,Formula 1 Qatar Airways Azerbaijan Grand Prix ...,15,2026-09-26,15,0,17,+44.230,1:46.336,...,Bortoleto,Brazil,2004-10-14,audi,Audi Revolut F1 Team,Germany,2026,NaN,NaN,https://en.wikipedia.org/wiki/Audi_in_Formula_One
15,2026,azerbaijan_2026,Formula 1 Qatar Airways Azerbaijan Grand Prix ...,15,2026-09-26,-,0,5,DNF (51),1:47.761,...,Norris,Great Britain,13/11/1999,mclaren,McLaren Formula 1 Team,Great Britain,1966,10.0,13.0,https://en.wikipedia.org/wiki/McLaren
16,2026,azerbaijan_2026,Formula 1 Qatar Airways Azerbaijan Grand Prix ...,15,2026-09-26,-,0,7,DNF (51),1:47.822,...,Gasly,France,07/02/1996,alpine,Alpine F1 Team,France,2021,NaN,NaN,https://en.wikipedia.org/wiki/Alpine_F1_Team
17,2026,azerbaijan_2026,Formula 1 Qatar Airways Azerbaijan Grand Prix ...,15,2026-09-26,-,0,9,DNF (51),1:48.484,...,Colapinto,Argentina,2003-05-27,alpine,Alpine F1 Team,France,2021,NaN,NaN,https://en.wikipedia.org/wiki/Alpine_F1_Team
18,2026,azerbaijan_2026,Formula 1 Qatar Airways Azerbaijan Grand Prix ...,15,2026-09-26,-,0,12,DNF (51),1:48.443,...,Albon,Thailand,1996-03-23,williams,Williams Racing,Great Britain,1977,9.0,7.0,https://en.wikipedia.org/wiki/Williams_Grand_P...
19,2026,azerbaijan_2026,Formula 1 Qatar Airways Azerbaijan Grand Prix ...,15,2026-09-26,-,0,21,DNF (51),1:50.968,...,Alonso,Spain,1981-07-29,aston_martin,Aston Martin F1 Team,Great Britain,1959,NaN,NaN,https://en.wikipedia.org/wiki/Aston_Martin_in_...
20,2026,azerbaijan_2026,Formula 1 Qatar Airways Azerbaijan Grand Prix ...,15,2026-09-26,-,0,22,DNF (51),1:51.723,...,Stroll,Canada,1998-10-29,aston_martin,Aston Martin F1 Team,Great Britain,1959,NaN,NaN,https://en.wikipedia.org/wiki/Aston_Martin_in_...
21,2026,azerbaijan_2026,Formula 1 Qatar Airways Azerbaijan Grand Prix ...,15,2026-09-26,-,0,19,DNF (51),1:48.852,...,Bottas,Finland,1989-08-28,cadillac,Cadillac Formula 1 Team,United States,2026,NaN,NaN,https://en.wikipedia.org/wiki/Cadillac_in_Form...

In [6]:
df.columns

Index(['season', 'raceId', 'raceName', 'round', 'date', 'position', 'points',
       'grid', 'time', 'fastLap', 'retired', 'driver.driverId',
       'driver.number', 'driver.shortName', 'driver.url', 'driver.name',
       'driver.surname', 'driver.nationality', 'driver.birthday',
       'team.teamId', 'team.teamName', 'team.nationality',
       'team.firstAppareance', 'team.constructorsChampionships',
       'team.driversChampionships', 'team.url'],
      dtype='object')

In [19]:
df[['raceId', 'position', 'points', 'driver.driverId', 'time', 'driver.number']]

,raceId,position,points,driver.driverId,time,driver.number
0,azerbaijan_2026,1,25,russell,1:38:02.143,63
1,azerbaijan_2026,2,18,max_verstappen,+0.196,33
2,azerbaijan_2026,3,15,hadjar,+10.704,6
3,azerbaijan_2026,4,12,leclerc,+14.136,16
4,azerbaijan_2026,5,10,antonelli,+14.512,12
5,azerbaijan_2026,6,8,hamilton,+22.382,44
6,azerbaijan_2026,7,6,lindblad,+31.159,36
7,azerbaijan_2026,8,4,ocon,+31.189,31
8,azerbaijan_2026,9,2,bearman,+31.929,87
9,azerbaijan_2026,10,1,sainz,+32.416,55
10,azerbaijan_2026,11,0,hulkenberg,+33.231,27
11,azerbaijan_2026,12,0,lawson,+34.013,30
12,azerbaijan_2026,13,0,piastri,+36.401,81
13,azerbaijan_2026,14,0,perez,+41.400,11
14,azerbaijan_2026,15,0,bortoleto,+44.230,5
15,azerbaijan_2026,-,0,norris,DNF (51),4
16,azerbaijan_2026,-,0,gasly,DNF (51),10
17,azerbaijan_2026,-,0,colapinto,DNF (51),43
18,azerbaijan_2026,-,0,albon,DNF (51),23
19,azerbaijan_2026,-,0,alonso,DNF (51),14
20,azerbaijan_2026,-,0,stroll,DNF (51),18
21,azerbaijan_2026,-,0,bottas,DNF (51),77

## Alonso results during 2026 F1 season

In [3]:
df_alonso_2026 = get_data("2026/drivers/alonso", api='f1_api')

In [5]:
df_alonso_2026.columns

Index(['sprintResult', 'race.raceId', 'race.name', 'race.round', 'race.date',
       'race.circuit.circuitId', 'race.circuit.name', 'race.circuit.country',
       'race.circuit.city', 'race.circuit.length', 'race.circuit.lapRecord',
       'race.circuit.firstParticipationYear', 'race.circuit.numberOfCorners',
       'race.circuit.fastestLapDriverId', 'race.circuit.fastestLapTeamId',
       'race.circuit.fastestLapYear', 'result.finishingPosition',
       'result.gridPosition', 'result.raceTime', 'result.pointsObtained',
       'result.retired', 'sprintResult.finishingPosition',
       'sprintResult.gridPosition', 'sprintResult.raceTime',
       'sprintResult.pointsObtained', 'sprintResult.retired',
       'driver.driverId', 'driver.name', 'driver.surname'],
      dtype='object')

In [24]:
columns = [
    'race.raceId',
    'race.round',
    'race.circuit.circuitId',
    'race.circuit.city',
    'result.finishingPosition',
    'result.startPosition',
    'result.pointsObtained',
    'driver.driverId'
]
df_alonso_2026['result.finishingPosition'] = df_alonso_2026['result.finishingPosition'].replace(['NC', '-'], 'DNF').fillna('DNF')
df_alonso_2026 = df_alonso_2026.rename(columns={'result.gridPosition': 'result.startPosition'})
df_alonso_2026[columns]

,race.raceId,race.round,race.circuit.circuitId,race.circuit.city,result.finishingPosition,result.startPosition,result.pointsObtained,driver.driverId
0,australian_2026,1,albert_park,Melbourne,DNF,17,0,alonso
1,chinese_2026,2,shanghai,Shanghai,DNF,18,0,alonso
2,japanese_2026,3,suzuka,Suzuka,18,21,0,alonso
3,miami_2026,4,miami,Miami,15,17,0,alonso
4,canadian_2026,5,gilles_villeneuve,Montreal,DNF,18,0,alonso
5,monaco_2026,6,monaco,Monte Carlo,10,21,1,alonso
6,catalunya_2026,7,montmelo,Barcelona,DNF,not available,0,alonso
7,austrian_2026,8,red_bull_ring,Spielberg,18,21,0,alonso
8,british_2026,9,silverstone,Silverstone,18,not available,0,alonso
9,belgian_2026,10,spa,Stavelot,19,22,0,alonso
10,hungarian_2026,11,hungaroring,Mogyorod,14,16,0,alonso
11,dutch_2026,12,zandvoort,Zandvoort,9,18,2,alonso
12,italian_2026,13,monza,Monza,DNF,not available,0,alonso
13,spanish_2026,14,madring,Madrid,17,17,0,alonso
14,azerbaijan_2026,15,baku,Baku,DNF,21,0,alonso

## Historical data of Singaporean Cirucit

In [25]:
df_Singapore = get_data('circuits/search', params={'q': 'singapore'}, api='f1_api')

In [26]:
df_Singapore

,circuitId,circuitName,country,city,circuitLength,lapRecord,firstParticipationYear,numberOfCorners,fastestLapDriverId,fastestLapTeamId,fastestLapYear,url
0,marina_bay,Marina Bay Street Circuit,Singapore,Singapore,4940,1:35:867,2008,19,hamilton,mercedes,2023,https://en.wikipedia.org/wiki/Marina_Bay_Stree...

In [34]:
races_list = []

for i in range(2008, 2027):
    df_season = get_data(str(i), api='f1_api')
    
    # Filtra solo Singapore
    df_sg = df_season[
        (df_season['circuit.circuitId'] == 'marina_bay') | 
        (df_season['circuit.city'] == 'Singapore')
    ]
    
    if not df_sg.empty:
        races_list.append(df_sg)

# Unisce tutto in un unico DataFrame
df_Singapore = pd.concat(races_list, ignore_index=True)
df_Singapore[['raceId', 'raceName', 'round', 'schedule.race.date', 'winner']]

KeyboardInterrupt:

In [35]:

df = get_data('2008', api='f1_api')
df

,raceId,championshipId,raceName,laps,round,url,winner,teamWinner,schedule.race.date,schedule.race.time,...,circuit.country,circuit.city,circuit.circuitLength,circuit.lapRecord,circuit.firstParticipationYear,circuit.corners,circuit.fastestLapDriverId,circuit.fastestLapTeamId,circuit.fastestLapYear,circuit.url
0,albert_park_2008,f1_2008,Australian Grand Prix,None,1,http://en.wikipedia.org/wiki/2008_Australian_G...,None,None,2008-03-16,04:30:00Z,...,Australia,Melbourne,5278km,1:19:813,1996.0,14.0,leclerc,ferrari,2024.0,https://en.wikipedia.org/wiki/Albert_Park_Circuit
1,sepang_2008,f1_2008,Malaysian Grand Prix,None,2,http://en.wikipedia.org/wiki/2008_Malaysian_Gr...,None,None,2008-03-23,07:00:00Z,...,Malaysia,Kuala Lumpur,nullkm,None,NaN,NaN,None,None,NaN,http://en.wikipedia.org/wiki/Sepang_Internatio...
2,bahrain_2008,f1_2008,Bahrain Grand Prix,None,3,http://en.wikipedia.org/wiki/2008_Bahrain_Gran...,None,None,2008-04-06,11:30:00Z,...,Bahrain,Sakhir,5412km,1:31:447,2004.0,15.0,de_la_rosa,mclaren,2005.0,http://en.wikipedia.org/wiki/Bahrain_Internati...
3,catalunya_2008,f1_2008,Spanish Grand Prix,None,4,http://en.wikipedia.org/wiki/2008_Spanish_Gran...,None,None,2008-04-27,12:00:00Z,...,Spain,Montmeló,nullkm,None,NaN,NaN,None,None,NaN,http://en.wikipedia.org/wiki/Circuit_de_Barcel...
4,istanbul_2008,f1_2008,Turkish Grand Prix,None,5,http://en.wikipedia.org/wiki/2008_Turkish_Gran...,None,None,2008-05-11,12:00:00Z,...,Turkey,Istanbul,5338km,1:24:770,2005.0,14.0,montoya,mclaren,2005.0,https://en.wikipedia.org/wiki/Istanbul_Park
5,monaco_2008,f1_2008,Monaco Grand Prix,None,6,http://en.wikipedia.org/wiki/2008_Monaco_Grand...,None,None,2008-05-25,12:00:00Z,...,Monaco,Monte Carlo,3337km,1:12:909,1950.0,19.0,hamilton,mercedes,2021.0,https://en.wikipedia.org/wiki/Circuit_de_Monaco
6,villeneuve_2008,f1_2008,Canadian Grand Prix,None,7,http://en.wikipedia.org/wiki/2008_Canadian_Gra...,None,None,2008-06-08,17:00:00Z,...,Canada,Montreal,nullkm,None,NaN,NaN,None,None,NaN,http://en.wikipedia.org/wiki/Circuit_Gilles_Vi...
7,magny_cours_2008,f1_2008,French Grand Prix,None,8,http://en.wikipedia.org/wiki/2008_French_Grand...,None,None,2008-06-22,12:00:00Z,...,France,Magny Cours,nullkm,None,NaN,NaN,None,None,NaN,http://en.wikipedia.org/wiki/Circuit_de_Nevers...
8,silverstone_2008,f1_2008,British Grand Prix,None,9,http://en.wikipedia.org/wiki/2008_British_Gran...,None,None,2008-07-06,12:00:00Z,...,Great Britain,Silverstone,5891km,1:27:097,1950.0,18.0,max_verstappen,red_bull,2020.0,https://en.wikipedia.org/wiki/Silverstone_Circuit
9,hockenheimring_2008,f1_2008,German Grand Prix,None,10,http://en.wikipedia.org/wiki/2008_German_Grand...,None,None,2008-07-20,12:00:00Z,...,Germany,Hockenheim,nullkm,None,NaN,NaN,None,None,NaN,http://en.wikipedia.org/wiki/Hockenheimring
10,hungaroring_2008,f1_2008,Hungarian Grand Prix,None,11,http://en.wikipedia.org/wiki/2008_Hungarian_Gr...,None,None,2008-08-03,12:00:00Z,...,Hungary,Mogyorod,4381km,1:16:627,1986.0,14.0,hamilton,mercedes,2020.0,https://en.wikipedia.org/wiki/Hungaroring
11,valencia_2008,f1_2008,European Grand Prix,None,12,http://en.wikipedia.org/wiki/2008_European_Gra...,None,None,2008-08-24,12:00:00Z,...,Spain,Valencia,nullkm,None,NaN,NaN,None,None,NaN,http://en.wikipedia.org/wiki/Valencia_Street_C...
12,spa_2008,f1_2008,Belgian Grand Prix,None,13,http://en.wikipedia.org/wiki/2008_Belgian_Gran...,None,None,2008-09-07,12:00:00Z,...,Belgium,Stavelot,7004km,1:46:286,1950.0,20.0,bottas,mercedes,2018.0,https://en.wikipedia.org/wiki/Circuit_de_Spa-F...
13,monza_2008,f1_2008,Italian Grand Prix,None,14,http://en.wikipedia.org/wiki/2008_Italian_Gran...,None,None,2008-09-14,12:00:00Z,...,Italy,Monza,5793km,1:21:046,1950.0,11.0,barrichelo,ferrari,2004.0,https://en.wikipedia.org/wiki/Monza_Circuit
14,marina_bay_2008,f1_2008,Singapore Grand Prix,None,15,http://en.wikipedia.org/wiki/2008_Singapore_Gr...,None,None,2008-09-28,12:00:00Z,...,Singapore,Singapore,4940km,1:35:867,2008.0,19.0,hamilton,mercedes,2023.0,https://en.wikipedia.org/wiki/Marina_Bay_Stree...
15,fuji_2008,f1_2008,Japanese Grand Prix,None,16,http://en.wikipedia.org/wiki/2008_Japanese_Gra...,None,None,2008-10-12,04:30:00Z,...,Japan,Oyama,nullkm,None,NaN,NaN,None,None,NaN,http://en.wikipedia.org/wiki/Fuji_Speedway
16,shanghai_2008,f1_2008,Chinese Grand Prix,None,17,http://en.wikipedia.org/wiki/2008_Chinese_Gran...,None,None,2008-10-19,07:00:00Z,...,China,Shanghai,5451km,1:32:238,2004.0,16.0,michael_schumacher,ferrari,2004.0,http://en.wikipedia.org/wiki/Shanghai_Internat...
17,interlagos_2008,f1_2008,Brazilian Grand Prix,None,18,http://en.wikipedia.org/wiki/2008_Brazilian_Gr...,None,None,2008-11-02,17:00:00Z,...,Brazil,Sao Paulo,4309km,1:10:540,1972.0,15.0,bottas,mercedes,2018.0,https://en.wikipedia.org/wiki/Interlagos_Circuit

In [6]:
df_Singapore = get_data('circuits/marina_bay/races', params={'limit': 100}, api='jolpica')
df_Singapore.columns
# df_Singapore[['season', 'round', 'raceName', 'date']]

Index(['season', 'round', 'url', 'raceName', 'date', 'time',
       'Circuit.circuitId', 'Circuit.url', 'Circuit.circuitName',
       'Circuit.Location.lat', 'Circuit.Location.long',
       'Circuit.Location.locality', 'Circuit.Location.country',
       'FirstPractice.date', 'SecondPractice.date', 'ThirdPractice.date',
       'Qualifying.date', 'FirstPractice.time', 'SecondPractice.time',
       'ThirdPractice.time', 'Qualifying.time', 'Sprint.date', 'Sprint.time',
       'SprintQualifying.date', 'SprintQualifying.time'],
      dtype='object')